name: Scheduled Mirroring

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Dependency Setup
        run: sudo apt update && sudo apt install just
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Main Function
        run: just
