name: Scheduled Mirroring

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: apt update && apt install just
      - run: just
