name: Scheduled Mirroring

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Dependency Setup
        run: sudo apt update && sudo apt install just
      - name: SSH Setup
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id
          ssh-keygen -f ~/.ssh/id -y > ~/.ssh/id.pub
      - name: Main Function
        run: just
